NPS : NET PROMOTOR SCORE:

1-6 RATING : DEMOTER/DTRACTOR
7-8 RATING : NEUTRAL
9-10 RATING : PROMOTORS


NPS = NO OF PROMOTORS - NO OF DETRACTORS/ TOTAL USERS


COMPANY DATASET  HAVING DATA ON CUSTOMER SATISFACTION AND CALCULATE NPS USING NUMPY


In [3]:
import numpy as np

In [2]:
survey = np.loadtxt('/content/survey.txt')
survey[:5]

array([ 7., 10.,  5.,  9.,  9.])

In [3]:
#What nupy technique to be used to filter out detractors

In [8]:

detractors = survey[survey <=6]

In [9]:
detractors

array([5., 4., 4., 5., 1., 5., 5., 1., 4., 5., 4., 4., 4., 5., 1., 4., 1.,
       4., 1., 5., 5., 1., 1., 4., 1., 5., 4., 1., 1., 4., 1., 5., 1., 4.,
       4., 1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 5., 5., 5., 4., 4., 1.,
       4., 1., 4., 1., 5., 1., 1., 5., 4., 4., 4., 4., 1., 4., 5., 4., 4.,
       1., 1., 5., 5., 1., 5., 1., 5., 5., 4., 5., 4., 1., 1., 1., 1., 4.,
       1., 4., 4., 5., 4., 1., 1., 1., 1., 5., 4., 5., 5., 4., 1., 5., 1.,
       4., 4., 1., 1., 1., 4., 4., 5., 5., 4., 5., 5., 5., 1., 4., 1., 5.,
       5., 1., 5., 1., 1., 5., 5., 4., 4., 1., 4., 4., 4., 1., 1., 4., 4.,
       4., 5., 5., 1., 1., 4., 1., 4., 1., 4., 1., 4., 1., 4., 1., 5., 4.,
       4., 5., 1., 4., 5., 5., 5., 1., 5., 4., 1., 1., 5., 5., 5., 4., 5.,
       4., 4., 1., 4., 4., 4., 4., 5., 1., 5., 5., 1., 4., 4., 5., 1., 1.,
       4., 5., 5., 5., 1., 4., 5., 5., 4., 1., 5., 5., 5., 1., 1., 5., 5.,
       1., 1., 1., 4., 5., 5., 4., 4., 4., 5., 1., 4., 1., 4., 5., 4., 5.,
       5., 1., 5., 1., 5.

In [10]:
detractors.shape

(332,)

Find promotor percentage [promotors > =9]

In [24]:

promoters = survey[survey >=9]
#promoter_percent = np.mean(promoters)*100
promotor_percent = round(promoters.shape[0]/survey.shape[0]*100,2)

In [23]:

#promoter_percent = np.mean(promoters)*100
detractor_percent = round(detractors.shape[0]/survey.shape[0]*100,2)

In [27]:
#NPS = PERCENTAGE OF (PROMOTORS) - PERCENTAGE OF (DETRACTORS)

In [28]:
NPS = promoter_percent - detractor_percent

In [29]:
NPS

np.float64(906.853776683087)

In [33]:
NPS = round(100*(promoters.shape[0]-detractors.shape[0])/survey.shape[0],2)

In [38]:
print("NPS = ",NPS,"%")

NPS =  23.74 %


FITNESS DATA


In [9]:
data = np.loadtxt('/fit.txt',dtype= str)
data[:5]

/tmp/ipykernel_852/2414674862.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data = np.loadtxt('/fit.txt',dtype= str)


array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [10]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [42]:
# AVERAGE STEP COUNT ON ACTIVE DAYS

In [12]:
step_count = data[:,1].astype(int)
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [13]:
# Approach 1 :
round(np.mean(step_count[data[:,5]=='Active']),2)

np.float64(3226.57)

In [14]:
# Approach 2 :
active_cases = data[:,5]

In [15]:
avg_Active_cases= step_count[active_cases=="Active"].mean()

In [16]:
round(avg_Active_cases,2)

np.float64(3226.57)

In [17]:
#How many days had more than 5000 steps and burned more than 150 calories?

In [20]:
calories_burned = data[:,3].astype(int)

In [21]:
np.sum((step_count > 5000) & (calories_burned > 150))

np.int64(17)

In [22]:
#What percentage of days had a "Sad" mood?

In [24]:
mood = data[:,2]

In [25]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [28]:
sad_percentage = round(100*(mood[mood == 'Sad'].shape[0]/data.shape[0]),2)

In [29]:
sad_percentage

30.21

In [30]:
#What is the maximum number of steps taken on days with less than 6 hours of sleep?

In [53]:
sleep = data[:,4].astype(int)
data[sleep]

array([['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['14-10-2

In [54]:
#step_count_1 = step_count[less_sleep]
step_count[sleep]

array([4545,   61, 4545, 6915, 4545, 4340, 4340, 1230, 4545, 4340,   61,
       4545, 4340, 1230, 4545, 4340,   61, 4545, 6915, 4545, 4340,   61,
       4545, 4340, 4545,   61, 4545, 6915, 4545, 6915, 4545, 6915, 5461,
         25, 1258, 4545, 4340, 6915, 4545,   61, 6915, 4545, 4340, 4545,
       4340, 4545, 4340, 4545, 4340, 4545, 4340, 1230, 4340, 1230, 4340,
       4545, 4340, 1230,   61,   61, 1230,   61, 4545, 6915, 5461, 5461,
       6915, 4545, 4545, 4545, 5461, 6915, 6915, 4545, 4545, 4545, 4545,
       4545, 4545, 6915, 5461, 6915, 4545, 4545, 6915, 4545, 5461, 5461,
       5461,   25, 5461,   25,   61, 4545, 4545, 4545])

In [56]:
max_steps = np.max(step_count[sleep<6])

In [57]:
print(f"Max Steps with less sleep then 6 hours = ",max_steps)

Max Steps with less sleep then 6 hours =  7422


In [52]:
#What are the average calories burned per hour of sleep on "Inactive" days

In [93]:
calories = data[:,3].astype(int)
calories

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [99]:
calories_mask = calories[data[:,5]=='Inactive']

In [100]:
sleep = data[:,4].astype(int)
sleep_mask= sleep[data[:,5]=='Inactive']

In [104]:
average_calories = round(np.mean(calories_mask/sleep_mask),2)
average_calories

np.float64(18.62)

In [106]:
print("Average Calories burned per hour of sleep on Inactive Days = ",average_calories)

Average Calories burned per hour of sleep on Inactive Days =  18.62


In [107]:
#On how many days was the mood "Sad" and sleep less than the median sleep?

In [119]:
np.sum((mood == 'Sad') & (sleep < np.median(sleep)))

np.int64(10)

In [120]:
#What is the standard deviation of step count only for "Happy" mood days?

In [121]:
np.std(step_count[data[:,2]=='Happy'])

np.float64(2088.4016254961593)

In [122]:
#What is the longest streak (in days) where 'Inactive' days had calories burned less than the daily mean across the full dataset?

In [131]:
# MEAN CALORIES ACROSS DATA
calories = data[:,3].astype(int)
calories_mean = np.mean(calories)

In [132]:
# identifying days matching both condition
conditions = (data[:,5]=='Inactive')&(calories_burned < calories_mean)



In [133]:
max_streak = 0
current_streak = 0

for i in conditions:
  if i :
    current_streak+=1
    max_streak = max(max_streak,current_streak)
  else :
    current_streak = 0


In [135]:
print("Longest Streak where 'Inactive' days had calories burned less than the daily mean: ",max_streak, " days")

Longest Streak where 'Inactive' days had calories burned less than the daily mean:  8  days


In [136]:
#On days when the person was 'Sad' and burned fewer than average calories, what is the median step count?

In [139]:
calories = data[:,3].astype(int)
avg_calories= np.mean(calories)

In [141]:
condition_2 = (data[:,2]== 'Sad') & (calories < avg_calories)

In [147]:
data_2 = data[condition_2]

In [154]:
median_step_count = np.median(data_2[:,1].astype(int))
print("Median Step Count : ",median_step_count," Steps")

Median Step Count :  651.0  Steps


In [155]:
#How many days had below-median step count, above-average sleep, and the mood was not 'Sad'?

In [193]:
# Median Step Count
median_step_count2 = np.median(data[:,1].astype(int))

# Avg_Sleep
average_sleep = np.mean(data[:,4].astype(int))

# Mood
mood = data[:,2]

In [198]:
condition_3 = ((step_count <median_step_count2) & (sleep > average_sleep) & (mood != 'Sad'))

In [203]:
days = np.sum(condition_3)

In [204]:
print("No of days : ",days)

No of days :  13
